name       : aseman-qt-tools
version    : 1.0.0
release    : 1
source     :
    - https://github.com/Aseman-Land/aseman-qt-tools/archive/v1.0.0-stable.tar.gz : 44ad93a205921ed920b7dbcca1ae4d8150d001b06d6f8f01e46da02cc607ece2
license    : GPL-3.0
component  : programming
summary    : AsemanQtTools, is the shared tools and functions, used in the aseman's projects.
description: |
    AsemanQtTools, is the shared tools and functions, used in the aseman's projects.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - qtkeychain-devel
setup      : |
    mkdir build && cd build
    qmake \
        QT+=dbus \
        QT+=multimedia \
        QT+=positioning \
        QT+=sensors \
        QT+=widgets \
        ../asemantools.pro
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install INSTALL_ROOT"=$installdir"
