name       : aseman-qt-tools
version    : 1.0.0
release    : 3
source     :
    - https://github.com/Aseman-Land/aseman-qt-tools/archive/v1.0.0-stable.tar.gz : 44ad93a205921ed920b7dbcca1ae4d8150d001b06d6f8f01e46da02cc607ece2
homepage   : https://github.com/Aseman-Land/aseman-qt-tools
license    : GPL-3.0-or-later
component  : programming
summary    : AsemanQtTools, is the shared tools and functions, used in the aseman's projects
description: |
    AsemanQtTools, is the shared tools and functions, used in the aseman's projects.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(gl)
    - qtkeychain-devel
setup      : |
    %patch -p1 < $pkgfiles/altlinux_alt-qt5.15.patch
    mkdir build && cd build
    qmake \
        QT+=dbus \
        QT+=multimedia \
        QT+=positioning \
        QT+=sensors \
        QT+=widgets \
        ../asemantools.pro
build      : |
    %make -C build
install    : |
    %make_install -C build INSTALL_ROOT"=$installdir"
